# CI Github Action
---
name: ci

on:
  pull_request:
    branches: [$default-branch]

jobs:
  style:
    name: Pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: analize with pylint
        run: pylint $(git ls-files app/*.py)
